### PR TITLE
Update nokogiri, mimemagic, minitest and dry-configurable

### PR DESCRIPTION
**Pull request by vlakre**
Update dry-configurable gem to remove deprication warning
Update default argument as per [changelog](https://github.com/dry-rb/dry-configurable/blob/master/CHANGELOG.md#changed-1)

Update nokogiri, mimemagic and minitest in order to update dry-configurable gem

### CODE REVIEW

**Review by d4be4st — APPROVED** [review]

**Comment by vlakre** [comment]
@d4be4st how do you, in this case when the dependency is updated, decide which version of the gem you will bump? 
I'm guessing that either minor or patch should be incremented?

**Comment by d4be4st** [comment]
Gemfile.lock does not affect your applications, it only affects running of the tests locally/on CI.
what is in your .gemspec are the version your applications take into account.

**Comment by vlakre** [comment]
But, since there are changes in these files: `lib/mailgun_catcher/engine.rb` and `lib/mailgun_catcher.rb`,
this gem should update version in order for my app to pick up those changes, right? 
Since I don't have it defined as `gem 'mailgun_catcher', git: ...` in the Gemfile

**Comment by d4be4st** [comment]
To pick up the changes you need to pull from rubygems
to pull from rubygems you need to release the new code
to release the new code you need a new version (rubygems will reject your gem if version is the same)

**Pull request merged**
